export const PROCESS_OBLIGATIONS_SCHEMA = "agent-fleet.process-obligations/v1" as const;
export type TaskRisk = "unknown" | "low" | "high";
export type TaskScope = "unknown" | "read-only" | "small" | "wide";
export type ObligationStatus = "satisfied" | "open" | "unsupported";
export type ProcessStage = "classify-risk" | "plan" | "execute" | "acceptance" | "review" | "complete";

export interface ProcessStageState { required: boolean; evidenceRef: string | null; revision: string | null; }
export interface ProcessObligationState {
 schema: typeof PROCESS_OBLIGATIONS_SCHEMA; risk: TaskRisk; scope: TaskScope;
 acceptance: ProcessStageState; review: ProcessStageState; plan: ProcessStageState;
 reassessments: number; lastReason: string | null; appliedRuleIds: string[]; changedFiles: string[];
}
export interface ProcessClassificationInput { risk?: string; scope?: string; reason?: string; newTask?: boolean; }
export interface ProcessVerdict {
 accepted: boolean; path: "read-only" | "changed-task"; risk: TaskRisk; scope: TaskScope; budgetTier: string;
 obligations: Record<"risk" | "acceptance" | "review" | "plan", { status: ObligationStatus; evidenceRef?: string }>;
 appliedRuleIds: string[]; currentStage: ProcessStage; admissibleNextAction: string; auditScope: string[]; explanation: string;
}
const RISKS = new Set<TaskRisk>(["unknown", "low", "high"]), SCOPES = new Set<TaskScope>(["unknown", "read-only", "small", "wide"]);
const scopeRank: Record<TaskScope, number> = { unknown: 0, "read-only": 0, small: 1, wide: 2 };
const cleanReason = (value: unknown) => typeof value === "string" && value.trim() ? value.trim().slice(0, 512) : null;
const strings = (value: unknown) => Array.isArray(value) ? [...new Set(value.filter(v => typeof v === "string" && v.trim()).map(v => v.trim()))].sort() : [];
export function createProcessState(): ProcessObligationState { return { schema: PROCESS_OBLIGATIONS_SCHEMA, risk: "unknown", scope: "unknown", acceptance: { required: true, evidenceRef: null, revision: null }, review: { required: false, evidenceRef: null, revision: null }, plan: { required: false, evidenceRef: null, revision: null }, reassessments: 0, lastReason: null, appliedRuleIds: ["risk-unknown-fail-closed"], changedFiles: [] }; }
export function normalizeProcessState(value: unknown): ProcessObligationState {
 const row = value && typeof value === "object" ? value as any : {}, state = createProcessState();
 if (RISKS.has(row.risk)) state.risk = row.risk; if (SCOPES.has(row.scope)) state.scope = row.scope;
 for (const key of ["acceptance", "review", "plan"] as const) { const stage = row[key] && typeof row[key] === "object" ? row[key] : {}; state[key] = { required: stage.required === true, evidenceRef: typeof stage.evidenceRef === "string" && stage.evidenceRef ? stage.evidenceRef : null, revision: typeof stage.revision === "string" && stage.revision ? stage.revision : null }; }
 state.reassessments = Number.isSafeInteger(row.reassessments) && row.reassessments >= 0 ? row.reassessments : 0; state.lastReason = cleanReason(row.lastReason);
 state.appliedRuleIds = strings(row.appliedRuleIds); state.changedFiles = strings(row.changedFiles); return state;
}
function rules(risk: TaskRisk, scope: TaskScope): string[] { return [...new Set([risk === "unknown" ? "risk-unknown-fail-closed" : risk === "high" ? "risk-high-independent-review" : "risk-low-minimal-acceptance", scope === "wide" ? "scope-wide-plan-review" : scope === "read-only" ? "scope-read-only-lightweight" : "scope-changed-task", "budget-tier-spend-only"])]; }
export function applyProcessClassification(current: ProcessObligationState, input: ProcessClassificationInput): { ok: true; state: ProcessObligationState; message: string } | { ok: false; state: ProcessObligationState; message: string } {
 const reason = cleanReason(input.reason); if (input.newTask && !reason) return { ok: false, state: normalizeProcessState(current), message: "A genuine new task requires a non-empty reason." };
 const base = input.newTask ? createProcessState() : normalizeProcessState(current), risk = input.risk === undefined ? base.risk : String(input.risk).trim().toLowerCase() as TaskRisk, scope = input.scope === undefined ? base.scope : String(input.scope).trim().toLowerCase() as TaskScope;
 if (!RISKS.has(risk)) return { ok: false, state: base, message: `risk must be one of unknown | low | high (got "${input.risk}").` }; if (!SCOPES.has(scope)) return { ok: false, state: base, message: `scope must be one of read-only | small | wide (got "${input.scope}").` };
 const riskWasExplicit = input.risk !== undefined, riskChanged = risk !== base.risk, scopeExpanded = scopeRank[scope] > scopeRank[base.scope];
 if ((riskChanged || scopeExpanded) && !reason) return { ok: false, state: base, message: `${riskChanged ? "Risk change" : "Scope expansion"} requires a non-empty reason.` }; if (scopeExpanded && base.scope !== "unknown" && !riskWasExplicit) return { ok: false, state: base, message: "Scope expansion requires explicit risk reassessment in the same set_task_tier call." };
 const next = normalizeProcessState(base); next.risk = risk; next.scope = scope; next.lastReason = reason ?? next.lastReason; next.appliedRuleIds = rules(risk, scope);
 if (riskWasExplicit && (riskChanged || scopeExpanded || !!reason) || scopeExpanded) next.reassessments++;
 if (risk === "high" || scope === "wide") next.review.required = true; if (scope === "wide") next.plan.required = true;
 if (scopeExpanded) { next.acceptance = { required: true, evidenceRef: null, revision: null }; if (next.review.required) next.review = { required: true, evidenceRef: null, revision: null }; if (next.plan.required) next.plan = { required: true, evidenceRef: null, revision: null }; }
 return { ok: true, state: next, message: `Process classified: risk ${next.risk}, scope ${next.scope}.` };
}
export function noteProcessStage(state: ProcessObligationState, stage: "acceptance" | "plan" | "review", evidence: { evidenceRef: string; revision: string; changedFiles?: string[] }): ProcessObligationState { const next = normalizeProcessState(state); if (next[stage].required && evidence.evidenceRef && evidence.revision) next[stage] = { required: true, evidenceRef: evidence.evidenceRef, revision: evidence.revision }; if (stage === "acceptance" && evidence.changedFiles) next.changedFiles = strings(evidence.changedFiles); return next; }
export function processOpenObligations(state: ProcessObligationState, revision?: string): string[] { const s = normalizeProcessState(state); return [s.risk === "unknown" ? "risk" : "", s.plan.required && !s.plan.evidenceRef ? "plan" : "", s.acceptance.required && (!s.acceptance.evidenceRef || revision && s.acceptance.revision !== revision) ? "acceptance" : "", s.review.required && (!s.review.evidenceRef || revision && s.review.revision !== revision) ? "review" : ""].filter(Boolean); }
export function processPreEffectGate(state: ProcessObligationState, effect: "write" | "child" | "prove", persona = "", revision?: string): { reason: string; message: string } | null { const s = normalizeProcessState(state); if ((effect === "write" || effect === "child") && s.plan.required && !s.plan.evidenceRef && persona !== "planner") return { reason: "process_plan_open", message: "Process gate refused the dependent effect: the wide-task plan obligation is open. Run the planner first." }; if (effect === "prove") { const open = processOpenObligations(s, revision).filter(x => x !== "acceptance"); if (open.length) return { reason: "process_obligations_open", message: `Assertion cannot become proven while process obligations are open: ${open.join(", ")}.` }; } return null; }
export function evaluateProcessObligations(state: ProcessObligationState, input: { writable: boolean; budgetTier: string; t2Accepted?: boolean; currentRevision?: string }): ProcessVerdict {
 const s = normalizeProcessState(state); if (!input.writable) return { accepted: false, path: "read-only", risk: s.risk, scope: s.scope, budgetTier: input.budgetTier, obligations: { risk: { status: "unsupported" }, acceptance: { status: "unsupported" }, review: { status: "unsupported" }, plan: { status: "unsupported" } }, appliedRuleIds: rules(s.risk, "read-only"), currentStage: "acceptance", admissibleNextAction: "continue read-only research; changed-task acceptance is unavailable", auditScope: [], explanation: `Read-only source-traceable path; T2 acceptance is unsupported and fails closed. Budget tier ${input.budgetTier} limits spend only.` };
 const status = (stage: ProcessStageState, revisionBound = true): ObligationStatus => !stage.required ? "satisfied" : stage.evidenceRef && (!revisionBound || !input.currentRevision || stage.revision === input.currentRevision) ? "satisfied" : "open";
 const obligations: ProcessVerdict["obligations"] = { risk: { status: s.risk === "unknown" ? "open" : "satisfied" }, acceptance: { status: input.t2Accepted || status(s.acceptance) === "satisfied" ? "satisfied" : "open", ...(s.acceptance.evidenceRef ? { evidenceRef: s.acceptance.evidenceRef } : {}) }, review: { status: status(s.review), ...(s.review.evidenceRef ? { evidenceRef: s.review.evidenceRef } : {}) }, plan: { status: status(s.plan, false), ...(s.plan.evidenceRef ? { evidenceRef: s.plan.evidenceRef } : {}) } };
 const open = Object.entries(obligations).filter(([,x]) => x.status !== "satisfied").map(([x]) => x), accepted = open.length === 0; const currentStage: ProcessStage = open.includes("risk") ? "classify-risk" : open.includes("plan") ? "plan" : open.includes("acceptance") ? "acceptance" : open.includes("review") ? "review" : "complete";
 const next = currentStage === "classify-risk" ? "set_task_tier with explicit risk and reason" : currentStage === "plan" ? "dispatch planner" : currentStage === "acceptance" ? "execute and verify the changed task" : currentStage === "review" ? "dispatch an independent reviewer over the current changed scope" : "report completion";
 return { accepted, path: "changed-task", risk: s.risk, scope: s.scope, budgetTier: input.budgetTier, obligations, appliedRuleIds: s.appliedRuleIds.length ? s.appliedRuleIds : rules(s.risk,s.scope), currentStage, admissibleNextAction: next, auditScope: s.changedFiles, explanation: `Risk ${s.risk} and scope ${s.scope} determine correctness obligations; budget tier ${input.budgetTier} limits spend only.${open.length ? ` Open: ${open.join(", ")}.` : " All obligations satisfied."}` };
}
export function processAllowsPersona(state: ProcessObligationState, persona: string): boolean { const name = String(persona||"").trim().toLowerCase(), s=normalizeProcessState(state); return s.plan.required && name === "planner" || s.review.required && ["code-reviewer","plan-reviewer","security-auditor"].includes(name); }
export function processAuditRecord(state: ProcessObligationState, verdict: ProcessVerdict) { return { schema: PROCESS_OBLIGATIONS_SCHEMA, risk: verdict.risk, scope: verdict.scope, budgetTier: verdict.budgetTier, obligations: Object.fromEntries(Object.entries(verdict.obligations).map(([k,v])=>[k,{status:v.status}])), appliedRuleIds: verdict.appliedRuleIds, currentStage: verdict.currentStage, admissibleNextAction: verdict.admissibleNextAction, auditScope: verdict.auditScope, explanation: verdict.explanation, state: normalizeProcessState(state) }; }
export function latestProcessState(entries: readonly unknown[]): ProcessObligationState { for(let i=entries.length-1;i>=0;i--){const row=entries[i] as any,type=row?.customType??row?.type;if(type!=="agent-hub-process-state")continue;const data=row?.data;if(data?.schema===PROCESS_OBLIGATIONS_SCHEMA)return normalizeProcessState(data.state??data);}return createProcessState(); }
