import test from 'node:test';import assert from 'node:assert/strict';import {createMonitorSessionBridge} from './monitor-session-bridge.ts';
test('bridge persists exact output chunks and cursors',async()=>{let saved:any={tasks:[]};const runtime={load:()=>saved,save:(v:any)=>saved=structuredClone(v)};const a:any=createMonitorSessionBridge({runtime});a.startParent({id:'p',hubInstanceId:'h',checkoutId:'c'});await a.startChild({key:'c',id:'c',generation:1,parentId:'p',parentGeneration:1,specialist:'x'},{});await a.appendOutput('c','one');await a.appendOutput('c','two');await a.appendOutput('c','three');const b:any=createMonitorSessionBridge({runtime});assert.equal(b.readOutput({taskId:'c',generation:1,afterSequence:2}).text,'three');assert.equal(b.readOutput({taskId:'c',generation:1,afterSequence:3}).text,'');});
test('same monitor key restart creates gen2 while preserving gen1 late history',async()=>{let saved:any={tasks:[]};const runtime={load:()=>saved,save:(v:any)=>saved=structuredClone(v)};const a:any=createMonitorSessionBridge({runtime});a.startParent({id:'p',hubInstanceId:'h',checkoutId:'c'});await a.startChild({key:'same',id:'run',generation:1,parentId:'p',parentGeneration:1,specialist:'x'},{});await a.finishChild('same','completed');a.recordComsLateEvent('same',{kind:'late'});a.snapshot();const b:any=createMonitorSessionBridge({runtime});await b.startChild({key:'same',id:'run',generation:1,parentId:'p',parentGeneration:1,specialist:'x'},{});await b.appendOutput('same','gen2');await b.finishChild('same','completed');const rows=b.snapshot().tasks.filter((t:any)=>t.id==='run');assert.deepEqual(rows.map((t:any)=>t.generation).sort(),[1,2]);assert.equal(b.readOutput({taskId:'run',generation:2,afterSequence:0}).text,'gen2');b.snapshot();const c:any=createMonitorSessionBridge({runtime});assert.equal(c.snapshot().tasks.filter((t:any)=>t.id==='run').length,2);});
test('finalize persists terminal output before its promise resolves',async()=>{let saved:any={tasks:[]};const runtime={load:()=>saved,save:(v:any)=>saved=structuredClone(v)};const a:any=createMonitorSessionBridge({runtime});a.startParent({id:'p',hubInstanceId:'h',checkoutId:'c'});const task=await a.startChild({key:'x',id:'x',generation:1,parentId:'p',parentGeneration:1,specialist:'s'},{});await a.finalizeChildFor(task,'final','completed');const b:any=createMonitorSessionBridge({runtime});const row=b.snapshot().tasks.find((t:any)=>t.id==='x');assert.equal(row.state,'completed');assert.equal(b.readOutput({taskId:'x',generation:1,afterSequence:0}).text,'final');});
test('initial owner binding patches preexisting parent across restart',()=>{let saved:any={tasks:[]};const runtime={load:()=>saved,save:(v:any)=>saved=structuredClone(v)};const a:any=createMonitorSessionBridge({runtime});a.startParent({id:'p',hubInstanceId:'h',checkoutId:'c'});a.setCurrentOwner({ownerSessionId:'owner',ownerLeaseExpiresAt:'2025-01-01T00:00:30Z',updateActive:true});const b:any=createMonitorSessionBridge({runtime});const row=b.snapshot().tasks.find((t:any)=>t.id==='p');assert.equal(row.ownerSessionId,'owner');assert.equal(row.ownerLeaseExpiresAt,'2025-01-01T00:00:30Z');});
test('bridge persists terminal output and restores cursor reads without duplicates',async()=>{let saved:any={tasks:[]};const runtime={load:()=>saved,save:(v:any)=>saved=structuredClone(v)};const a:any=createMonitorSessionBridge({runtime});a.startParent({id:'p',hubInstanceId:'h',checkoutId:'c',workspaceId:'w',hubPaneId:'pane'});await a.startChild({key:'c',id:'c',generation:1,parentId:'p',parentGeneration:1,specialist:'x'},{});await a.appendOutput('c','one');await a.cancelWaitOnly('c',{kind:'late'});const b:any=createMonitorSessionBridge({runtime});assert.equal(b.readOutput({taskId:'c',generation:1,afterSequence:0}).text,'one');assert.equal(b.readOutput({taskId:'c',generation:1,afterSequence:1}).text,'');assert.equal(b.snapshot().tasks.find((t:any)=>t.id==='c').state,'cancelled');});

test('session reset preserves durable monitor keys for the next hub process',async()=>{let saved:any={tasks:[]};const runtime={load:()=>saved,save:(v:any)=>saved=structuredClone(v)};const first:any=createMonitorSessionBridge({runtime});first.startParent({id:'old-parent',hubInstanceId:'h',checkoutId:'c'});const old=await first.startChild({key:'builder:1',id:'run-builder-1',generation:1,parentId:'old-parent',specialist:'builder'},{});await first.finalizeChildFor(old,'done','completed');first.reset();assert.equal(saved.tasks.find((task:any)=>task.id==='run-builder-1').monitorKey,'builder:1');});

test('a legacy journal without monitor keys advances a reused run id generation instead of crashing',async()=>{let saved:any={tasks:[{id:'old-parent',generation:1,kind:'parent',state:'completed',hubInstanceId:'h',checkoutId:'c'},{id:'run-builder-1',generation:1,kind:'child',state:'completed',parentId:'old-parent',parentGeneration:1,specialist:'builder'}]};const runtime={load:()=>saved,save:(v:any)=>saved=structuredClone(v)};const bridge:any=createMonitorSessionBridge({runtime});bridge.startParent({id:'new-parent',hubInstanceId:'h',checkoutId:'c'});const task=await bridge.startChild({key:'builder:1',id:'run-builder-1',generation:1,parentId:'new-parent',specialist:'builder'},{});assert.equal(task.generation,2);assert.equal(saved.tasks.find((row:any)=>row.id==='run-builder-1'&&row.generation===2).monitorKey,'builder:1');});
