import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { createMonitorLifecycle } from "./monitor-lifecycle.ts";

test("lifecycle renews before expiry and clears timer plus owned discovery on stop", async () => {
 const timers:any[]=[]; let renewed=0,cleaned=0; const socketPath=join(mkdtempSync(join(tmpdir(),"monitor-lease-")),"s");
 const registration:any={profileKey:"p",token:"t",socketPath,socketDir:dirname(socketPath),snapshot:()=>({tasks:[]}),leaseMs:20,renew:()=>renewed++,cleanup:()=>cleaned++};
 const lifecycle=createMonitorLifecycle({registry:{register:()=>registration},setInterval:(fn:any,ms:number)=>{timers.push({fn,ms,cleared:false});return timers.length-1;},clearInterval:(id:number)=>{timers[id].cleared=true;}});
 await lifecycle.startBridge({snapshot:()=>({tasks:[]}),readOutput:()=>({})},{profilePath:"/tmp/fake",hubInstanceId:"hub"});
 assert.equal(timers[0].ms,10); timers[0].fn(); assert.equal(renewed,1);
 await lifecycle.stop(); assert.equal(timers[0].cleared,true); assert.equal(cleaned,1);
});

test("renewal errors disable the monitor and clean owned resources", async () => { const timers:any[]=[];let cleaned=0;const socketPath=join(mkdtempSync(join(tmpdir(),"monitor-renew-error-")),"s");const registration:any={profileKey:"p",token:"t",socketPath,socketDir:dirname(socketPath),snapshot:()=>({}),leaseMs:20,renew:()=>{throw Error("lost owner")},cleanup:()=>cleaned++};const lifecycle:any=createMonitorLifecycle({registry:{register:()=>registration},setInterval:(fn:any)=>{timers.push(fn);return 0},clearInterval:()=>{}});await lifecycle.startBridge({snapshot:()=>({}),readOutput:()=>({})},{profilePath:"/tmp/fake",hubInstanceId:"hub"});timers[0]();await new Promise(resolve=>setImmediate(resolve));assert.equal(lifecycle.isUnavailable(),true);assert.equal(cleaned,1);});

test("reconciliation scheduler waits 30s, recurs, and stops with lifecycle", async () => { const timers:any[]=[];const socketPath=join(mkdtempSync(join(tmpdir(),"monitor-reconcile-clock-")),"s");const registration:any={profileKey:"p",token:"t",socketPath,socketDir:dirname(socketPath),snapshot:()=>({}),leaseMs:1_000_000,renew:()=>{},cleanup:()=>{}};let calls=0;const lifecycle:any=createMonitorLifecycle({registry:{register:()=>registration},setInterval:(fn:any,ms:number)=>{timers.push({fn,ms,cleared:false});return timers.length-1},clearInterval:(id:number)=>{timers[id].cleared=true},getRecoveryEvidence:async(task:any)=>({owner:true,task})});try{await lifecycle.startBridge({snapshot:()=>({tasks:[{id:"task",generation:1}]}),readOutput:()=>({}),prune:()=>{},reconcile:()=>calls++},{profilePath:"/tmp/fake",hubInstanceId:"hub"});const reconcile=timers.find(t=>t.ms===30_000);assert.ok(reconcile);assert.equal(calls,0);reconcile.fn();await new Promise(resolve=>setImmediate(resolve));assert.equal(calls,1);reconcile.fn();await new Promise(resolve=>setImmediate(resolve));assert.equal(calls,2);await lifecycle.stop();assert.equal(reconcile.cleared,true);}finally{await lifecycle.stop();}});

test("active owner defers startup until lease expiry and stop cancels retry",async()=>{let now=0,calls=0;const timers:any[]=[];const socketPath=join(mkdtempSync(join(tmpdir(),"monitor-retry-")),"s");const registration:any={profileKey:"p",token:"t",socketPath,socketDir:dirname(socketPath),snapshot:()=>({}),cleanup:()=>{}};const lifecycle:any=createMonitorLifecycle({now:()=>now,registry:{register:()=>{calls++;if(calls===1){const e:any=Error("active");e.leaseExpiresAt=new Date(30_000).toISOString();throw e;}return registration;}},setTimeout:(fn:any,ms:number)=>{timers.push({fn,ms,cleared:false});return timers.length-1},clearTimeout:(id:number)=>{timers[id].cleared=true},setInterval:()=>0,clearInterval:()=>{}});assert.equal(await lifecycle.startBridge({snapshot:()=>({}),readOutput:()=>({}),prune:()=>{},reconcile:()=>{}},{profilePath:"/tmp/fake",hubInstanceId:"hub"}),null);assert.equal(calls,1);assert.equal(timers[0].ms,30_000);now=29_999;assert.equal(calls,1);now=30_000;timers[0].fn();await Promise.resolve();assert.equal(calls,2);await lifecycle.stop();assert.equal(timers[0].cleared,false);});

test("stopped deferred lease retry never recreates lifecycle resources",async()=>{let calls=0;const timers:any[]=[];const lifecycle:any=createMonitorLifecycle({now:()=>0,registry:{register:()=>{calls++;const e:any=Error();e.leaseExpiresAt=new Date(30_000).toISOString();throw e;}},setTimeout:(fn:any)=>{timers.push(fn);return 0},clearTimeout:()=>{},setInterval:()=>0,clearInterval:()=>{}});await lifecycle.startBridge({snapshot:()=>({}),readOutput:()=>({}),prune:()=>{},reconcile:()=>{}},{profilePath:"/tmp/fake",hubInstanceId:"h"});await lifecycle.stop();timers[0]();await Promise.resolve();assert.equal(calls,1);});

test("successful lease retry reinstalls bridge owner cancel and reconciliation hooks",async()=>{let calls=0;const timers:any[]=[];const socketPath=join(mkdtempSync(join(tmpdir(),"monitor-retry-hooks-")),"s");const reg:any={profileKey:"p",token:"t",ownerId:"owner",leaseExpiresAt:new Date(30_000).toISOString(),socketPath,socketDir:dirname(socketPath),snapshot:()=>({}),leaseMs:1000,renew:()=>{},cleanup:()=>{}};const lifecycle:any=createMonitorLifecycle({now:()=>0,registry:{register:()=>{calls++;if(calls===1){const e:any=Error();e.leaseExpiresAt=new Date(30_000).toISOString();throw e;}return reg;}},setTimeout:(fn:any,ms:number)=>{timers.push({fn,ms});return timers.length-1},clearTimeout:()=>{},setInterval:(fn:any,ms:number)=>{timers.push({fn,ms});return timers.length-1},clearInterval:()=>{}});let owner:any;const bridge:any={snapshot:()=>({}),readOutput:()=>({}),prune:()=>{},reconcile:()=>{},setCurrentOwner:(v:any)=>owner=v,cancelTask:()=>({})};await lifecycle.startBridge(bridge,{profilePath:"/tmp/fake",hubInstanceId:"h"});timers[0].fn();await new Promise(resolve=>setImmediate(resolve));assert.equal(calls,2);assert.deepEqual(owner,{ownerSessionId:"owner",ownerLeaseExpiresAt:reg.leaseExpiresAt,updateActive:true});assert.equal(typeof reg.cancel,"function");assert.ok(timers.some(t=>t.ms===30_000));await lifecycle.stop();});

test('deferred recovery probe cannot mutate a stopped lifecycle',async()=>{const timers:any[]=[];let resolve:any,calls=0;const socketPath=join(mkdtempSync(join(tmpdir(),'monitor-probe-')),'s');const reg:any={profileKey:'p',token:'t',socketPath,socketDir:dirname(socketPath),leaseMs:1e6,renew:()=>{},cleanup:()=>{}};const lifecycle:any=createMonitorLifecycle({registry:{register:()=>reg},setInterval:(fn:any,ms:number)=>{timers.push({fn,ms});return timers.length-1},clearInterval:()=>{},getRecoveryEvidence:()=>new Promise(r=>resolve=r)});const bridge:any={snapshot:()=>({tasks:[{id:'x',generation:1}]}),prune:()=>{},readOutput:()=>({}),reconcile:()=>calls++,cancelTask:()=>({})};try{await lifecycle.startBridge(bridge,{profilePath:'/tmp/fake',hubInstanceId:'h'});timers.find(t=>t.ms===30_000).fn();await lifecycle.stop();resolve({owner:false,socket:false,session:false,herdr:false});await new Promise(r=>setImmediate(r));assert.equal(calls,0);}finally{await lifecycle.stop();}});

test('stale deferred socket startup cleans resources without hooks',async()=>{let resolve:any,closed=0,cleaned=0,owner=0;const timers:any[]=[];const reg:any={profileKey:'p',token:'t',socketPath:'/tmp/s',socketDir:'/tmp',leaseMs:100,renew:()=>{},cleanup:()=>cleaned++};const lifecycle:any=createMonitorLifecycle({registry:{register:()=>reg},createSocketServer:()=>({listen:()=>new Promise(r=>resolve=r),close:async()=>closed++}),setInterval:(fn:any)=>{timers.push(fn);return 0},clearInterval:()=>{}});const bridge:any={snapshot:()=>({}),prune:()=>{},readOutput:()=>({}),setCurrentOwner:()=>owner++,cancelTask:()=>({})};const pending=lifecycle.startBridge(bridge,{profilePath:'/tmp/fake',hubInstanceId:'h'});await lifecycle.stop();resolve();assert.equal(await pending,null);assert.equal(closed,1);assert.equal(cleaned,1);assert.equal(owner,0);assert.equal(timers.length,0);});

test("lifecycle cleans owned discovery when socket startup fails", async () => {
 let cleaned=0; const lifecycle=createMonitorLifecycle({registry:{register:()=>({profileKey:"p",token:"t",socketPath:"/no/such/dir/socket",socketDir:"/no/such/dir",snapshot:()=>({}),cleanup:()=>cleaned++})}});
 await assert.rejects(lifecycle.startBridge({snapshot:()=>({}),readOutput:()=>({})},{profilePath:"/tmp/fake",hubInstanceId:"hub"})); assert.equal(cleaned,1);
});
