export type MonitorTaskState = "starting" | "running" | "cancelling" | "completed" | "blocked" | "failed" | "cancelled" | "orphaned" | "recovering";
export const TERMINAL_TASK_STATES = new Set<MonitorTaskState>(["completed","blocked","failed","cancelled","orphaned"]);export type MonitorTaskKind="parent"|"child";
export interface MonitorTask{id:string;generation:number;kind:MonitorTaskKind;state:MonitorTaskState;parentId?:string;parentGeneration?:number;hubInstanceId?:string;checkoutId?:string;specialist?:string;workspaceId?:string;hubPaneId?:string;ownerSessionId?:string;ownerLeaseExpiresAt?:string;}
export interface CreateParentTaskInput{id:string;generation:number;hubInstanceId:string;checkoutId:string;ownerSessionId?:string;ownerLeaseExpiresAt?:string;}
export interface CreateChildTaskInput{id:string;generation:number;parentId:string;parentGeneration:number;specialist:string;workspaceId?:string;hubPaneId?:string;ownerSessionId?:string;ownerLeaseExpiresAt?:string;}
function requireStableIdentity(id:string,generation:number){if(!id)throw Error("task id is required");if(!Number.isInteger(generation)||generation<1)throw Error("task generation must be a positive integer");}const owner=(i:any)=>({...((i.ownerSessionId)?{ownerSessionId:i.ownerSessionId}:{}),...((i.ownerLeaseExpiresAt)?{ownerLeaseExpiresAt:i.ownerLeaseExpiresAt}:{})});
export function createParentTask(input:CreateParentTaskInput):MonitorTask{requireStableIdentity(input.id,input.generation);if(!input.hubInstanceId||!input.checkoutId)throw Error("parent correlation is required");return{id:input.id,generation:input.generation,kind:"parent",state:"starting",hubInstanceId:input.hubInstanceId,checkoutId:input.checkoutId,...owner(input)};}
export function createChildTask(input:CreateChildTaskInput):MonitorTask{requireStableIdentity(input.id,input.generation);if(!input.parentId||!Number.isInteger(input.parentGeneration)||input.parentGeneration<1||!input.specialist)throw Error("child hierarchy is required");return{id:input.id,generation:input.generation,kind:"child",state:"starting",parentId:input.parentId,parentGeneration:input.parentGeneration,specialist:input.specialist,...(input.workspaceId?{workspaceId:input.workspaceId}:{}),...(input.hubPaneId?{hubPaneId:input.hubPaneId}:{}),...owner(input)};}
export function transitionTask(task:MonitorTask,state:MonitorTaskState):MonitorTask{if(TERMINAL_TASK_STATES.has(task.state))throw Error(`terminal task ${task.id} cannot mutate`);if(state==="starting")throw Error("tasks cannot transition back to starting");return{...task,state};}export function continueTask(task:MonitorTask):MonitorTask{if(task.state!=="blocked")throw Error(`only blocked task ${task.id} can continue`);return{...task,generation:task.generation+1,state:"starting"};}

export const MONITOR_EVENT_SCHEMA="agent-fleet.monitor-event" as const;
export const MONITOR_EVENT_KINDS=new Set(["hub.turn_started","hub.turn_completed","hub.queue_depth_changed","hub.capability_changed","task.started","task.state_changed","task.output_advanced","task.late_event","task.generation_superseded","owner.lease_changed","owner.recovering","owner.orphaned","action.requested","action.accepted","action.rejected","action.completed"]);
export const MONITOR_INVOKE_ACTIONS=new Set(["request_status","request_verification","narrow_scope","request_research","request_specialist"]);
const id=(v:unknown,max=128)=>typeof v==="string"&&v.length>0&&v.length<=max&&/^[A-Za-z0-9][A-Za-z0-9._:-]*$/.test(v);
const positive=(v:unknown)=>Number.isInteger(v)&&(v as number)>0&&(v as number)<=1_000_000_000;
export function normalizeIngressTaskState(value:unknown):MonitorTaskState|null{return value==="done"?"completed":typeof value==="string"&&(["starting","running","cancelling","completed","blocked","failed","cancelled","orphaned","recovering"] as string[]).includes(value)?value as MonitorTaskState:null;}
export function validateMonitorEvent(value:unknown):any|null{const v=value as any;if(!v||v.schema!==MONITOR_EVENT_SCHEMA||v.schemaVersion!==1||!id(v.eventId)||!positive(v.eventSequence)||!id(v.profileKey,80)||!id(v.hubInstanceId)||!id(v.ownerId)||typeof v.occurredAt!=="string"||Number.isNaN(Date.parse(v.occurredAt))||!MONITOR_EVENT_KINDS.has(v.kind)||!id(v.materialKey,256))return null;if(v.task!==undefined){if(!v.task||!id(v.task.id)||!positive(v.task.generation)||(v.task.outputSequence!==undefined&&(!Number.isInteger(v.task.outputSequence)||v.task.outputSequence<0))||(v.task.toState!==undefined&&normalizeIngressTaskState(v.task.toState)!==v.task.toState))return null;}return structuredClone(v);}
export function validateMonitorInvoke(value:unknown):any|null{const v=value as any;if(!v||!id(v.requestId)||!id(v.taskId)||!positive(v.generation)||!MONITOR_INVOKE_ACTIONS.has(v.action)||!v.parameters||typeof v.parameters!=="object"||!v.basis||v.basis.judgment!=="confirmed"||typeof v.basis.deviation!=="string"||v.basis.deviation.length>64)return null;const p=v.parameters;if(Object.keys(p).some(k=>!["assertionIds","evidenceEventIds","instruction"].includes(k))||!Array.isArray(p.assertionIds)||p.assertionIds.length>20||!Array.isArray(p.evidenceEventIds)||p.evidenceEventIds.length>20||p.assertionIds.some((x:unknown)=>!id(x,64))||p.evidenceEventIds.some((x:unknown)=>!id(x,128))||(p.instruction!==undefined&&(typeof p.instruction!=="string"||p.instruction.length>1024)))return null;return structuredClone(v);}
