import React, { useEffect, useState } from 'react';
// Self-contained dashboard bundle: Hermes loads this file without relative-module resolution.
const present=value=>{if(value?.error)return{kind:'error',message:value.error};if(value?.loading)return{kind:'loading'};return value?.tasks?.length?{kind:'tasks',tasks:value.tasks}:{kind:'empty'};};

const bounded=(text='')=>String(text).slice(-8192);
function hierarchy(tasks){const roots=[], parents=new Map();for(const task of tasks){if(task.kind==='parent'){const row={...task,children:[]};parents.set(`${task.hubInstanceId}:${task.id}:${task.generation}`,row);roots.push(row)}}for(const task of tasks.filter(t=>t.kind!=='parent')){const parent=parents.get(`${task.hubInstanceId}:${task.parentId}:${task.parentGeneration}`);if(parent)parent.children.push(task);else roots.push({...task,children:[]})}return roots}
function Pane({ctx}) {
 const [value,setValue]=useState({loading:true});
 useEffect(()=>{const documentRef=globalThis.document;let live=true, visible=!!documentRef&&documentRef.visibilityState!=='hidden', timer=null, inFlight=false, epoch=0;const cursors=new Map();
  const output=async(row,cursor,pollEpoch)=>{const result=await ctx.rest(`/output?task_id=${encodeURIComponent(row.id)}&generation=${encodeURIComponent(row.generation)}&after_sequence=${encodeURIComponent(cursor)}${row.hubInstanceId?`&hub_instance_id=${encodeURIComponent(row.hubInstanceId)}`:''}`);if(!live||!visible||pollEpoch!==epoch)return; cursors.set(`${row.hubInstanceId}:${row.id}:${row.generation}`,result.sequence??cursor);setValue(old=>({tasks:(old.tasks??[]).map(t=>t.hubInstanceId===row.hubInstanceId&&t.id===row.id&&t.generation===row.generation?{...t,output:bounded(`${t.output??''}${result.text??''}`),outputSequence:result.sequence??t.outputSequence,outputFirstSequence:result.firstSequence,truncated:!!result.truncated}:t)}));};
  const poll=async()=>{if(!visible||inFlight)return;inFlight=true;const pollEpoch=++epoch;try{const snapshot=await ctx.rest('/snapshot');if(!live||!visible||pollEpoch!==epoch)return;const tasks=snapshot.tasks??[];setValue(old=>{const cached=new Map((old.tasks??[]).map(t=>[`${t.hubInstanceId}:${t.id}:${t.generation}`,t]));return{tasks:tasks.map(t=>{const prior=cached.get(`${t.hubInstanceId}:${t.id}:${t.generation}`);return prior&&prior.outputSequence===t.outputSequence?{...t,output:prior.output,outputFirstSequence:prior.outputFirstSequence}:t;})}});for(const row of tasks){const key=`${row.id}:${row.generation}`,cursor=cursors.get(`${row.hubInstanceId}:${key}`)??0;if((row.outputSequence??0)>cursor)await output(row,cursor,pollEpoch)}}catch(error){live&&visible&&setValue({error:String(error)})}finally{inFlight=false}};
  const start=()=>{if(!timer)timer=setInterval(()=>void poll(),1000)}; const change=()=>{visible=documentRef?.visibilityState==='visible';epoch++;if(visible)start();else if(timer){clearInterval(timer);timer=null}};if(visible)start();void poll();documentRef?.addEventListener('visibilitychange',change);return()=>{live=false;if(timer)clearInterval(timer);documentRef?.removeEventListener('visibilitychange',change)};
 },[ctx]);
 const view=present(value);if(view.kind!=='tasks')return React.createElement('div',{role:view.kind==='error'?'alert':'status'},view.message??view.kind);
 const cancel=(task)=>ctx.rest(`/cancel?task_id=${encodeURIComponent(task.id)}&generation=${encodeURIComponent(task.generation)}${task.hubInstanceId?`&hub_instance_id=${encodeURIComponent(task.hubInstanceId)}`:''}`,{method:'POST'});
 const row=(task)=>React.createElement('li',{role:'treeitem',key:`${task.hubInstanceId}:${task.id}:${task.generation}`},`${task.id} · ${task.generation??''} · ${task.state}${task.state==='recovering'?' · Recovering connection':task.state==='orphaned'?' · Task orphaned':''} ${task.output??''}${task.truncated?' [output truncated]':''}`,task.canCancel&&task.state!=='orphaned'?React.createElement('button',{'aria-label':`Cancel ${task.id} generation ${task.generation}`,onClick:()=>cancel(task),onKeyDown:e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();cancel(task)}}},'Cancel'):null,task.children?.length?React.createElement('ul',{role:'group'},...task.children.map(row)):null);
 return React.createElement('ul',{role:'tree','aria-label':'Agent Fleet tasks'},...hierarchy(view.tasks).map(row));
}
export default {id:'agent-fleet-monitor',register(ctx){ctx.register({id:'pane',area:'panes',title:'Agent Fleet Monitor',render:()=>React.createElement(Pane,{ctx})})}};
