import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {MonitorRegistry} from './hermes-monitor-registry.ts';
import {MonitorStore,MAX_OUTPUT_BYTES} from './hermes-monitor-store.ts';
import {MonitorRuntime} from '../../.pi/harnesses/agent-hub/monitor-runtime.ts';
import {MonitorPublisher} from '../../.pi/harnesses/agent-hub/monitor-publisher.ts';
import {FakeHerdrServer} from './fake-herdr-server.ts';
import {MonitorSocketServer} from './hermes-monitor-socket.ts';
import * as net from 'node:net';

test('registry isolates two profiles and two hubs with colliding task IDs',()=>{const root=mkdtempSync(join(tmpdir(),'monitor-e2e-'));const registry=new MonitorRegistry({runtimeDir:root,leaseMs:30_000}),snapshot=()=>({tasks:[]});const a=registry.register({profilePath:'/tmp/a',profileId:'a',hubInstanceId:'hub-a',snapshot}),b=registry.register({profilePath:'/tmp/a',profileId:'a',hubInstanceId:'hub-b',snapshot}),c=registry.register({profilePath:'/tmp/b',profileId:'b',hubInstanceId:'hub-a',snapshot});assert.notEqual(a.token,b.token);assert.notEqual(a.socketPath,b.socketPath);assert.notEqual(a.namespacePath,c.namespacePath);assert.ok((a.renew() as any).leaseExpiresAt);a.cleanup();b.cleanup();c.cleanup();});

test('two concurrent active tasks use generation CAS, cursors, bounded output, and no cross-task mutation',()=>{const s=new MonitorStore();s.createParent({id:'p',generation:1,hubInstanceId:'h',checkoutId:'c'} as any);for(const id of ['a','b'])s.createChild({id,generation:1,parentId:'p',parentGeneration:1,specialist:'fake',hubInstanceId:'h'} as any);s.appendPublicOutput('a',1,'a1');s.appendPublicOutput('a',1,'a2');assert.equal(s.readOutput('a',1,1).text,'a2');s.appendPublicOutput('b',1,'x'.repeat(MAX_OUTPUT_BYTES+1));assert.equal(s.readOutput('b',1,0).truncated,true);s.transition('a',1,'cancelled');assert.throws(()=>s.transition('a',1,'completed'));assert.equal(s.get('b',1)?.state,'starting');});

test('fake Herdr correlates concurrent children to one workspace pane with cursor output',async t=>{const fake=await FakeHerdrServer.start({paneId:'pane',workspaceId:'workspace',resyncOutput:{sequence:2,text:'resync'}});t.after(()=>fake.close());const store=new MonitorStore(),pub=new MonitorPublisher(store),env={HERDR_ENV:'1',HERDR_PANE_ID:'pane',HERDR_SOCKET_PATH:fake.socketPath} as any;const p=pub.publishParent({id:'p',generation:1,hubInstanceId:'h',checkoutId:'c'});const [a,b]=await Promise.all(['a','b'].map(id=>pub.publishChildForHub({id,generation:1,parentId:p.id,parentGeneration:p.generation,specialist:'fake',hubInstanceId:'h'},env)));assert.equal(a.workspaceId,'workspace');assert.equal(b.hubPaneId,'pane');pub.publishPublicOutput(a.id,a.generation,'one');assert.equal(store.readOutput(a.id,a.generation,0).sequence,1);assert.ok(fake.requests.some(r=>r.method==='pane.get'));});

test('owner-only UDS rejects forged routes and cancels only exact owned generation',async t=>{const root=mkdtempSync(join(tmpdir(),'monitor-e2e-uds-')),registry=new MonitorRegistry({runtimeDir:root}),reg:any=registry.register({profilePath:join(root,'profile'),profileId:'p',hubInstanceId:'h',snapshot:()=>({tasks:[]})});let cancelled=0,workspaceClose=0;reg.output=(r:any)=>r.taskId==='task'&&r.generation===1?{sequence:r.afterSequence+1,text:'out'}:Promise.reject(Error('bad task'));reg.cancel=(r:any)=>{if(r.taskId==='task'&&r.generation===1){cancelled++;return{cancelled:true}}return{cancelled:false,reason:'unsupported'}};const server=new MonitorSocketServer(reg);await server.listen();t.after(async()=>{await server.close();reg.cleanup()});const ask=(frame:any)=>new Promise<any>((resolve,reject)=>{let text='';const c=net.createConnection(reg.socketPath);c.on('connect',()=>c.end(JSON.stringify(frame)+'\n'));c.on('data',d=>text+=d);c.on('close',()=>resolve(JSON.parse(text)));c.on('error',reject)});assert.ok((await ask({type:'output',token:'wrong',taskId:'task',generation:1,afterSequence:0})).error);assert.notEqual((await ask({type:'cancel',token:reg.token,taskId:'other',generation:1})).result?.cancelled,true);assert.notEqual((await ask({type:'cancel',token:reg.token,taskId:'task',generation:2})).result?.cancelled,true);assert.equal((await ask({type:'output',token:reg.token,taskId:'task',generation:1,afterSequence:0})).output.text,'out');assert.equal((await ask({type:'cancel',token:reg.token,taskId:'task',generation:1})).result.cancelled,true);assert.equal(cancelled,1);assert.equal(workspaceClose,0);});

test('restart journal preserves cursor chunks and per-task 30 second orphan lease',()=>{const root=mkdtempSync(join(tmpdir(),'monitor-e2e-runtime-'));const r=new MonitorRuntime({runtimeDir:root,profileId:'p',hubInstanceId:'h',now:()=>new Date(30_000)});r.save({tasks:[{id:'x',generation:1,state:'running',outputChunks:[{sequence:1,text:'one'},{sequence:2,text:'two'}],outputLatestSequence:2,ownerLeaseExpiresAt:new Date(31_000).toISOString()},{id:'old',generation:1,state:'running',ownerLeaseExpiresAt:new Date(29_000).toISOString()}]});const state=r.load();assert.equal(state.tasks[0].outputChunks[1].sequence,2);const out=r.reconcile(state,{owner:false,socket:false,session:false,herdr:false});assert.equal(out.tasks.find((t:any)=>t.id==='x').state,'running');assert.equal(out.tasks.find((t:any)=>t.id==='old').state,'orphaned');});
